name: Build Electron App
on:
  pull_request:
    types: [closed]
jobs:
  build:
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'master'
    runs-on: macos-10.15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm run make
